### ISSUE TITLE
android:theme="@style/AppTheme"位置引发的问题

### ISSUE THREAD

**Issue by lindaojiang** [singwhatiwanna/dynamic-load-apk#35]
若在application标签下放置android:theme则会引发java.lang.RuntimeException: Binary XML file line #31: You must supply a layout_height attribute.这个错误
若去掉application下的android:theme则正常
出问题的文件1 AndroidManifest.xml
<application
    android:allowBackup="true"
    android:icon="@drawable/ic_launcher"
    android:label="@string/app_name"
    android:theme="@style/AppTheme" >  
    <activity
        android:name="com.ryg.dynamicload.sample.mainhost.MainActivity"
        android:label="@string/app_name" >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />

```
        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
</activity>
```

没问题的文件2 AndroidManifest.xml  
<application
    android:allowBackup="true"
    android:icon="@drawable/ic_launcher"
    android:label="@string/app_name" >
    <activity
        android:name="com.ryg.dynamicload.sample.mainhost.MainActivity"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />

```
        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
</activity>     
```

错误日志  
11-26 13:56:50.531  29391-29391/com.abc.soft D/DLPluginManager﹕ launch com.ryg.dynamicload.sample.mainplugin.MainActivity
11-26 13:56:50.581  29391-29391/com.abc.soft D/DLProxyImpl﹕ mClass=com.ryg.dynamicload.sample.mainplugin.MainActivity mPackageName=com.ryg.dynamicload.sample.mainplugina
11-26 13:56:50.581  29391-29391/com.abc.soft D/DLProxyImpl﹕ handleActivityInfo, theme=16973836
11-26 13:56:50.586  29391-29391/com.abc.soft D/DLProxyImpl﹕ instance = com.ryg.dynamicload.sample.mainplugin.MainActivity@4250c3c8
11-26 13:56:50.586  29391-29391/com.abc.soft D/DLBasePluginActivity﹕ attach: proxyActivity= com.ryg.dynamicload.DLProxyActivity@42508be8
11-26 13:56:50.586  29391-29391/com.abc.soft D/DLBasePluginActivity﹕ onCreate: from= FROM_EXTERNAL
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ java.lang.RuntimeException: Binary XML file line #31: You must supply a layout_height attribute.
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:492)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6187)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6355)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1837)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1749)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:58)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at android.view.LayoutInflater.rInflate(LayoutInflater.java:768)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3296)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3359)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:381)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:375)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at android.app.Activity.setContentView(Activity.java:2053)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at com.ryg.dynamicload.sample.mainplugin.MainActivity.initView(MainActivity.java:31)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at com.ryg.dynamicload.sample.mainplugin.MainActivity.onCreate(MainActivity.java:27)
11-26 13:56:50.591  29391-29391/com.abc.soft W/System.err﹕ at com.ryg.dynamicload.internal.DLProxyImpl.launchTargetActivity(DLProxyImpl.java:114)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at com.ryg.dynamicload.internal.DLProxyImpl.onCreate(DLProxyImpl.java:97)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at com.ryg.dynamicload.DLProxyActivity.onCreate(DLProxyActivity.java:45)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at android.app.Activity.performCreate(Activity.java:5453)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at android.app.ActivityThread.access$900(ActivityThread.java:175)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at android.os.Looper.loop(Looper.java:146)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5602)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
11-26 13:56:50.596  29391-29391/com.abc.soft W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)

**Comment by achellies** [comment]
透明背景如何解决呢？
