### ISSUE TITLE
虽然new了一个AssertManager，但native还是同一个资源管理器，插件和宿主apk会有资源id冲突的可能。

### ISSUE THREAD

**Issue by Everloster** [singwhatiwanna/dynamic-load-apk#38]

**Comment by HeLiHuang** [comment]
> 我是在使用LayoutInflater直接用代理的Context加载一个view的时候发现的，不过我找到了一个比较好的解决办法。 @OverRide public Object getSystemService(String name) { if (LAYOUT_INFLATER_SERVICE.equals(name)) { if (mInflater == null) { mInflater = LayoutInflater.from(mBase).cloneInContext(this); } return mInflater; } return super.getSystemService(name); } 把LayoutInflater也代理掉，这样插件apk也可以正常的使用LayoutInflater 和 代理Context来加载一个layout

这个完整代码能贴一下吗？整个类的
