### ISSUE TITLE
Jar文件过大

### ISSUE THREAD

**Issue by LiushuiXiaoxia** [singwhatiwanna/dynamic-load-apk#77]
你好，我用的是mac上的Androidstudio，编译生成的lib.jar和doi-common.jar有25G大，每个jar文件大约12.5G，这个太夸张了吧。

**Comment by singwhatiwanna** [comment]
@LiushuiXiaoxia dl目前对as的编译脚本有问题，eclipse是ok的。请留下你的qq，我来和你具体沟通。

**Comment by LiushuiXiaoxia** [comment]
qq:215266092
